---
title: "MF_physiochemical"
author: "Tim L"
date: '2022-08-27'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


###Load Packages
```{r}
library(dplyr)
library(ggplot2)
library(tidyverse)
```

###Read in data
```{r}
MFpc <- read.csv("AllTrials_pH_PS_MS_110822.csv", na.strings = c("", "NA"))
```

###pH plot
```{r}
MFpH <- MFpc %>% 
  filter(!is.na(pH)) %>% 
  filter(GramNeg == "KEEP") %>% 
  mutate(Day = as.factor(Day)) %>% 
  group_by(Day)



ggplot(data = MFpH, aes(x = factor(Day), y = pH, fill = factor(StorageTemp))) +
  geom_boxplot() +
  facet_grid(MFpH$PoreSize) +
  scale_fill_manual(values=c("#56B4E9", "#F0E442", "#D55E00")) +
  theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
  xlab("Day") + ylab("pH") +
  labs(color = "Storage Temperature (°C)", fill = "Storage Temperature (°C)") +
  scale_y_continuous(limits = c(5, 7))

ggsave("MFporesizepH_111522.jpeg", device = "png", type = "cairo")

ggplot(data = MFpH, aes(x = factor(Day), y = pH, fill = factor(StorageTemp))) +
  geom_boxplot() +
  facet_grid(MFpH$MilkType) +
  scale_fill_manual(values=c("#56B4E9", "#F0E442", "#D55E00")) +
  theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
  xlab("Day") + ylab("pH") +
  labs(color = "Storage Temperature (°C)", fill = "Storage Temperature (°C)") +
  scale_y_continuous(limits = c(5, 7))

ggsave("MFmilktypepH_111522.jpeg", device = "png", type = "cairo")
```

###Particle Size plot
```{r}
MFps <- MFpc %>% 
  filter(!is.na(ParticleSize)) %>% 
  filter(GramNeg == "KEEP") %>% 
  mutate(ParticleSize = as.numeric(as.character(ParticleSize))) %>% 
  mutate(ParticleSize = log10(ParticleSize)) %>% 
  mutate(Day = as.factor(Day)) %>% 
  group_by(Day) %>% 
  filter(!is.na(ParticleSize)) %>% 
  mutate(MilkType = replace(MilkType, MilkType == "skim ", "skim"))


ggplot(data = MFps, aes(x = factor(Day), y = ParticleSize, fill = factor(StorageTemp))) +
  geom_boxplot() +
  facet_grid(MFps$PoreSize) +
  scale_fill_manual(values=c("#56B4E9", "#F0E442", "#D55E00")) +
  theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
  xlab("Day") + 
  ylab(expression("Effective Diameter"~(log[10]~ nm))) +
  labs(color = "Storage Temperature (°C)", fill = "Storage Temperature (°C)") +
  scale_y_continuous(limits = c(2, 5))

ggsave("MFporesizeparticle.jpeg", device = "png", type = "cairo")

ggplot(data = MFps, aes(x = factor(Day), y = ParticleSize, fill = factor(StorageTemp))) +
  geom_boxplot() +
  facet_grid(MFps$MilkType) +
  scale_fill_manual(values=c("#56B4E9", "#F0E442", "#D55E00")) +
  theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
  xlab("Day") + 
  ylab(expression("Effective Diameter"~(log[10]~ nm))) +
  labs(color = "Storage Temperature (°C)", fill = "Storage Temperature (°C)") +
  scale_y_continuous(limits = c(2, 5))

ggsave("MFMilkTypeparticle.jpeg", device = "png", type = "cairo")



MFps3 <- MFps %>% 
  filter(StorageTemp == 3)

ggplot(data = MFps, aes(x = factor(Day), y = ParticleSize, fill = factor(PoreSize))) +
  geom_violin() +
  scale_fill_manual(values=c("#56B4E9", "#D55E00")) +
  theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
  xlab("Day") + 
  ylab(expression("Effective Diameter"  ~~log[10]~ (nm))) +
  labs(color = "Storage Temperature (°C)", fill = "Storage Temperature (°C)") +
  scale_y_continuous(limits = c(0, 3))

ggsave("MFps_082722.png", device = "png", type = "cairo")
```

###milkoscan
```{r}
components <- MFpc %>% 
  filter(!is.na(CompMethod)) %>% 
  filter(CompMethod == "milkoscan") %>% 
  group_by(Trial, PoreSize, MilkType) %>% 
  summarise_at(c("Fat", "Protein", "Lactose", "TS", "SnF"), mean, na.rm = TRUE)

componentsall <- components %>% 
  ungroup() %>% 
  group_by(PoreSize, MilkType) %>% 
  summarise_at(c("Fat", "Protein", "Lactose", "TS", "SnF"), mean, na.rm = TRUE) 

mfreduct <- components %>% 
  filter(MilkType == "rawskim" | MilkType == "mfskim")

  
```

###pH and Particle size
```{r}
poreph <- MFpH %>% 
  group_by(PoreSize) %>% 
  summarise(mean(pH))

porephrange <- MFpH %>% group_by(PoreSize) %>% 
  summarise(range(pH))

milkph <- MFpH %>% 
  group_by(MilkType) %>% 
  summarise(mean(pH))

milkphrange <- MFpH %>% group_by(MilkType) %>% 
  summarise(range(pH))

storageph <- MFpH %>% 
  group_by(StorageTemp) %>% 
  summarise(mean(pH))

storagephrange <- MFpH %>% group_by(StorageTemp) %>% 
  summarise(range(pH))

porePS <- MFps %>% 
  group_by(PoreSize) %>% 
  summarise(mean(ParticleSize))

porePSrange <- MFps %>% group_by(PoreSize) %>% 
  summarise(range(ParticleSize))

milkPS <- MFps %>% 
  group_by(MilkType) %>% 
  summarise(mean(ParticleSize))

milkpsrange <- MFps %>% group_by(MilkType) %>% 
  summarise(range(ParticleSize))

storageps <- MFps %>% 
  group_by(StorageTemp) %>% 
  summarise(mean(ParticleSize))

storagepsrange <- MFps %>% group_by(StorageTemp) %>% 
  summarise(range(ParticleSize))

coagulated <- MFps %>%
  filter(ParticleSize > 3.00) %>% 
  group_by(Trial, StorageTemp, PoreSize, MilkType, Day) %>% 
  summarise(mean(ParticleSize))



```

