---
title: "mfALLSum"
author: "Tim L"
date: "052522"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown                      

```{r}
library(dplyr)
library(tidyverse)
library(ggplot2)
library(wesanderson)
library(lme4)
library(emmeans)
library(lmerTest)
library(effectsize)
```

##Read in and check data
```{r}
mfALLpc <- read.csv("MF_ALL_110822.csv", na.strings = c("", "NA"))


mfkeep <- mfALLpc %>% 
  filter(ExtraInfo != "TNTC" & ExtraInfo != "PPC" & ExtraInfo != "ERROR")
```

```{r}
##MF APC jitter plots w/ trendline, one for each temperature (3C, 6.5C, 10C), separated by milk type

#Mutate data to summarize APC data grouped by Trial, Pore Size, Storage Temperature, and Day
mfrepslog <- mfkeep %>% 
  filter(MilkType == "Skim" | MilkType == "Whole") %>% 
  filter(PlateType == "SPC") %>% 
  filter(!is.na(StorageTemp)) %>% 
  mutate(Concentration = replace(Concentration, Concentration==0, 5)) %>% 
  mutate(Concentration = log10(Concentration)) %>%
  group_by(Trial, PoreSize, MilkType, StorageTemp, Day) %>% 
  summarise_at(c("Concentration"), mean, na.rm = TRUE) %>% 
  mutate(PoreSize = factor(PoreSize)) %>% 
  mutate(StorageTemp = factor(StorageTemp)) %>% 
  mutate(Day = as.character(Day)) %>% 
  mutate(Day = as.numeric(Day)) %>% 
  mutate(Trial = factor(Trial))

#3C APC plot (All trials)
mfrepslog3 <- mfALLpc %>% 
  filter(MilkType == "Skim" | MilkType == "Whole") %>% 
  filter(PlateType == "SPC") %>% 
  filter(!is.na(StorageTemp)) %>% 
  mutate(Concentration = replace(Concentration, Concentration==0, 5)) %>% 
  mutate(Concentration = log10(Concentration)) %>% 
  group_by(Trial, PoreSize, MilkType, StorageTemp, Day) %>% 
  summarise_at(c("Concentration"), mean, na.rm = TRUE) %>% 
  mutate(PoreSize = factor(PoreSize)) %>% 
  mutate(StorageTemp = factor(StorageTemp)) %>% 
  mutate(Day = as.character(Day)) %>% 
  mutate(Day = as.numeric(Day)) %>% 
  mutate(Trial = factor(Trial)) %>% 
  filter(StorageTemp == 3)

ggplot(data=mfrepslog3, aes(x=as.numeric(Day), y=Concentration, color = PoreSize)) +
  geom_jitter() +
  facet_grid(MilkType ~ ., scales = "free_y") +
scale_y_continuous(limits = c(0,10), breaks = c(1,2,3,4,5,6,7,8,9), expand = c(0, 0)) +
scale_x_continuous(breaks = c(0,7,14,21,28,35,42,49,56,63)) +
scale_color_manual(values = c("#E69F00", "#0072B2")) +
ggtitle("(a)") +
theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
xlab("Days") + ylab(expression(~~log[10]~ cfu/mL)) +
  geom_smooth(se = FALSE) +
  theme(plot.title = element_text(hjust = 0)) +
  theme(axis.text=element_text(size=10))


ggsave("mfALL3C-geomjitter_trendline.jpeg", device = "jpg", type = "cairo")


#6.5C APC Plot
mfrepslog6.5 <- mfALLpc %>% 
  filter(MilkType == "Skim" | MilkType == "Whole") %>% 
  filter(PlateType == "SPC") %>% 
  filter(!is.na(StorageTemp)) %>% 
  mutate(Concentration = replace(Concentration, Concentration==0, 5)) %>% 
  mutate(Concentration = log10(Concentration)) %>% 
  group_by(Trial, PoreSize, MilkType, StorageTemp, Day) %>% 
  summarise_at(c("Concentration"), mean, na.rm = TRUE) %>% 
  mutate(PoreSize = factor(PoreSize)) %>% 
  mutate(StorageTemp = factor(StorageTemp)) %>% 
  mutate(Day = as.character(Day)) %>% 
  mutate(Day = as.numeric(Day)) %>% 
  mutate(Trial = factor(Trial)) %>% 
  filter(StorageTemp == 6.5)

ggplot(data=mfrepslog6.5, aes(x=as.numeric(Day), y=Concentration, color = PoreSize)) +
  geom_jitter() +
  facet_grid(MilkType ~ ., scales = "free_y") +
scale_y_continuous(limits = c(0,10), breaks = c(1,2,3,4,5,6,7,8,9), expand = c(0, 0)) +
scale_x_continuous(breaks = c(0,7,14,21,28,35,42,49,56,63)) +
scale_color_manual(values = c("#E69F00", "#0072B2")) +
ggtitle("(b)") +
theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
xlab("Days") + ylab(expression(~~log[10]~ cfu/mL)) +
  geom_smooth(se = FALSE) +
  theme(axis.text=element_text(size=10)) +
  theme(plot.title = element_text(hjust = 0))

ggsave("mfALL6.5C-geomjitter_trendline.jpeg", device = "jpg", type = "cairo")

#10C APC plot
mfrepslog10 <- mfALLpc %>% 
  filter(MilkType == "Skim" | MilkType == "Whole") %>% 
  filter(PlateType == "SPC") %>% 
  filter(!is.na(StorageTemp)) %>% 
  mutate(Concentration = replace(Concentration, Concentration==0, 5)) %>% 
  mutate(Concentration = log10(Concentration)) %>% 
  group_by(Trial, PoreSize, MilkType, StorageTemp, Day) %>% 
  summarise_at(c("Concentration"), mean, na.rm = TRUE) %>% 
  mutate(PoreSize = factor(PoreSize)) %>% 
  mutate(StorageTemp = factor(StorageTemp)) %>% 
  mutate(Day = as.character(Day)) %>% 
  mutate(Day = as.numeric(Day)) %>% 
  mutate(Trial = factor(Trial)) %>% 
  filter(StorageTemp == 10)

ggplot(data=mfrepslog10, aes(x=as.numeric(Day), y=Concentration, color = PoreSize)) +
  geom_jitter() +
  facet_grid(MilkType ~ ., scales = "free_y") +
scale_y_continuous(limits = c(0,10), breaks = c(1,2,3,4,5,6,7,8,9), expand = c(0, 0)) +
scale_x_continuous(breaks = c(0,7,14,21,28,35,42,49,56,63)) +
scale_color_manual(values = c("#E69F00", "#0072B2")) +
ggtitle("(c)") +
theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
xlab("Days") + ylab(expression(~~log[10]~ cfu/mL)) +
  geom_smooth(se = FALSE) +
    theme(axis.text=element_text(size=10)) +
  theme(plot.title = element_text(hjust = 0))

ggsave("mfALL10C-geomjitter_trendline.jpeg", device = "jpg", type = "cairo")
```

##Isolate Characterization
```{r}
#Find top 3 days for each combination of Pore Size-Milk Type-Storage Temperature-Day to be used for selecting isolates for characterization
mfALLapcAvg <- mfrepslog %>% 
  group_by(Trial, PoreSize, MilkType, StorageTemp, Day) %>% 
  mutate(APCavg = mean(Concentration, na.rm = TRUE)) %>%
  summarize(APCavg) %>% 
  distinct()

#find maximum values APC for each HTST, Storage Temp, trial combo 
mfALLapcMax <- mfALLapcAvg %>% 
  ungroup() %>% 
  group_by(Trial, PoreSize, MilkType, StorageTemp) %>%
  top_n(3, APCavg) %>% 
  arrange(Trial, PoreSize, MilkType, StorageTemp)

#create table
write.csv(mfALLapcMax, file = "mfALLapcMax3_101122.csv")
```


##Attempt at ANOVA
```{r}
mflogAPC_aov <- mfkeep %>% 
  filter(MilkType == "Skim" | MilkType == "Whole") %>% 
  filter(PlateType == "SPC") %>% 
  filter(!is.na(StorageTemp)) %>% 
  mutate(Concentration = replace(Concentration, Concentration==0, 5)) %>% 
  mutate(Concentration = log10(Concentration)) %>% 
  group_by(PoreSize, MilkType, StorageTemp, Day, Trial) %>% 
  mutate(PoreSize = factor(PoreSize)) %>% 
  mutate(StorageTemp = factor(StorageTemp)) %>% 
  mutate(Day = as.character(Day)) %>% 
  mutate(Day = as.numeric(Day))



APCobservations <- mflogAPC_aov %>% 
  group_by(Trial, PoreSize, MilkType, StorageTemp, Day) %>% 
  summarise(n = n())

#check for interaction between pore size and storage temp
Poresize_StorTemp <- mflogAPC_aov %>% 
  group_by(PoreSize, StorageTemp) %>% 
  summarise_at(c("Concentration"), mean, na.rm = TRUE)


ggplot(data=Poresize_StorTemp, aes(x=StorageTemp, y=Concentration, group = PoreSize)) +
geom_line((aes(color = factor(PoreSize))))

APCaov <- lmer(Concentration ~ PoreSize + MilkType + StorageTemp + Day + StorageTemp*Day + StorageTemp*PoreSize + (1|Trial) + (1|Trial:PoreSize) + (1|Trial:PoreSize:MilkType) + (1|Trial:PoreSize:MilkType:StorageTemp) + (1|Trial:PoreSize:MilkType:StorageTemp:Day), data = mflogAPC_aov)

hist(resid(APCaov), breaks = 40)
plot(predict(APCaov), resid(APCaov))

mflogAPC_aov$residuals <- resid(APCaov)

anova(APCaov)

summary(APCaov)


emmeans(APCaov, ~ PoreSize + StorageTemp + Day + MilkType, at = list(Day = c(0, 7, 14, 21, 28, 35, 42, 49, 56, 63)))

emmip(APCaov, StorageTemp ~ Day | MilkType + PoreSize, at = list(Day = c(0, 35, 63)))

#milk type not significant in model, so this shows average of milk type
emmip(APCaov, StorageTemp ~ Day | PoreSize, at = list(Day = c(0, 35, 63))) #CIs = TRUE)

emmeans(APCaov,  pairwise ~ MilkType |  StorageTemp | Day | PoreSize, adjust = "none")

emmeans(APCaov, pairwise ~ StorageTemp)

emmeans(APCaov, pairwise ~ PoreSize)

eta_squared(APCaov, partial = FALSE)
```


```{r}

mflogAPCmax <- mflogAPC_aov %>% 
  group_by(PoreSize, MilkType, StorageTemp, Trial) %>% 
  summarise(max = max(Concentration))
  

mflogAPCmaxmeanST <- mflogAPCmax %>% 
  ungroup() %>% 
  group_by(StorageTemp) %>% 
  summarise(mean(max))

mflogAPCmaxsdST <- mflogAPCmax %>% 
  ungroup() %>% 
  group_by(StorageTemp) %>% 
  summarise(sd(max))


mflogAPCmaxmeanPS <- mflogAPCmax %>% 
  ungroup() %>% 
  group_by(PoreSize) %>% 
  summarise(mean(max))

mflogAPCmaxsdPS <- mflogAPCmax %>% 
  ungroup() %>% 
  group_by(PoreSize) %>% 
  summarise(sd(max))

mflogAPCmaxmeanMT <- mflogAPCmax %>% 
  ungroup() %>% 
  group_by(MilkType) %>% 
  summarise(mean(max))

mflogAPCmaxsdMT <- mflogAPCmax %>% 
  ungroup() %>% 
  group_by(MilkType) %>% 
  summarise(sd(max))

```

```{r}
##Currently Unused Plots

#3C APC by pore size
ggplot(data=mfrepslog, aes(x=as.numeric(Day), y=Concentration, color = MilkType)) +
  geom_point() +
  facet_grid(PoreSize ~ ., scales = "free_y") +
scale_y_continuous(limits = c(0,6), breaks = c(1,2,3,4,5,6,7,8,9), expand = c(0, 0)) +
scale_x_continuous(breaks = c(0,7,14,21,28,35,42,49,56,63)) +
scale_color_manual(values=wes_palette("BottleRocket1")) +
ggtitle("3C") +
theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
xlab("Day") + ylab(expression(~~Log[10]~ CFU/mL))

#6.5C APC by pore size
ggplot(data=mfrepslog6.5, aes(x=as.numeric(Day), y=Concentration, color = MilkType)) +
  geom_point() +
  facet_grid(PoreSize ~ ., scales = "free_y") +
scale_y_continuous(limits = c(0,10), breaks = c(1,2,3,4,5,6,7,8,9), expand = c(0, 0)) +
scale_x_continuous(breaks = c(0,7,14,21,28,35,42,49,56,63)) +
scale_color_manual(values=wes_palette("BottleRocket1")) +
ggtitle("6.5C") +
theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
xlab("Day") + ylab(expression(~~Log[10]~ CFU/mL))

#10C APC by pore size
ggplot(data=mfrepslog10, aes(x=as.numeric(Day), y=Concentration, color = MilkType)) +
  geom_jitter() +
  facet_grid(PoreSize ~ ., scales = "free_y") +
scale_y_continuous(limits = c(0,10), breaks = c(1,2,3,4,5,6,7,8,9), expand = c(0, 0)) +
scale_x_continuous(breaks = c(0,7,14,21,28,35,42,49,56,63)) +
scale_color_manual(values=wes_palette("BottleRocket1")) +
ggtitle("10C") +
theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
xlab("Day") + ylab(expression(~~Log[10]~ CFU/mL))

```


```{r}
#3C APC plot (All trials)
ggplot(data=mfrepslog10, aes(x=Day, y=Concentration, color = PoreSize, group = interaction(Trial, PoreSize, MilkType, StorageTemp))) +
  geom_jitter() +
  geom_path() +
  facet_grid(MilkType ~ ., scales = "free_y") +
scale_y_continuous(limits = c(0,6), breaks = c(1,2,3,4,5,6,7,8,9), expand = c(0, 0)) +
scale_x_continuous(breaks = c(0,7,14,21,28,35,42,49,56,63)) +
scale_color_manual(values=wes_palette("Cavalcanti1")) +
ggtitle("3C") +
theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
xlab("Day") + ylab(expression(~~Log[10]~ CFU/mL)) +
  geom_smooth(se = FALSE)



```

