---
title: "ESL_ModeltoThreshold"
author: "Tim L"
date: "11/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#packages
```{r}
library(tidyverse);library(lmerTest);library(data.table);library(knitr);library(emmeans)
library(patternplot);library(car);library(multcomp);library(dplyr);library(ggpubr);library(stringi)
library(nlsMicrobio);library(minpack.lm);library(AICcmodavg); library(grid); library(Ryacas); library(biogrowth); library(MASS)

```

###Read in Data
```{r}
##Filter by storage/HTST temp
mfALLpc <- read.csv("ShelfLife_Data.csv", na.strings = c("", "NA"))

#remove TNTC, PPC, and Lab Errors
mfkeep <- mfALLpc %>% 
  filter(ExtraInfo != "TNTC" & ExtraInfo != "PPC" & ExtraInfo != "ERROR")
```

###Read in Models

##Buchanan Log10
```{r}
# buchanan (in log10 scale)
buchanan_log10 <- LOG10N ~
  LOG10N0 + #base population
  (t >= lag) * (t <= (lag + (LOG10Nmax - LOG10N0) / mumax)) * #if in growth phase
  mumax * (t - lag) + #log-linear growth (assume positive)
  (t >= lag) * (t > (lag + (LOG10Nmax - LOG10N0) / mumax)) * # if in stationary phase (first condition unnecessary)
  (LOG10Nmax - LOG10N0) #take value of Nmax
```

##Gompertz log10
```{r}
# gompertzm (in log10 scale)
gompertzm_log10 <- LOG10N ~ LOG10N0 + 
  (LOG10Nmax - LOG10N0) * exp(-exp(mumax * exp(1) * (lag - t)/((LOG10Nmax - LOG10N0)) + 1))
```

##Baranyi log10
```{r}
# baranyi (in log10 scale)
# (mumax*log(10))
baranyi_log10 <- LOG10N ~ LOG10Nmax + 
  log10((-1 + exp((mumax*log(10)) * lag) + exp((mumax*log(10)) * t))/(exp((mumax*log(10)) * t) - 1 + exp((mumax*log(10)) * lag) * 10^(LOG10Nmax - LOG10N0)))
```


###0.8-Whole-10-Overall
```{r}

#0.8-Whole-10c
W0.8_10 <- mfkeep %>% 
  filter(StorageTemp == 10) %>% 
  filter(PoreSize == 0.8) %>% 
  filter(MilkType == "Whole") %>% 
  filter(PlateType == "SPC") %>% 
  dplyr::select(Concentration, Day) %>% 
  filter(!is.na(Concentration)) %>% 
  mutate(Day = Day*24) %>% 
  rename(t = Day) %>% 
  mutate(Concentration = replace(Concentration, Concentration==0, 2.5)) %>%
  mutate(Concentration = log10(Concentration)) %>% 
  rename(LOG10N = Concentration)

W0.8_10hrs <- W0.8_10[c("LOG10N", "t")]

#reorder by column index
W0.8_10hrs <- W0.8_10hrs[c(2,1)]

W0.8_10hrs <- W0.8_10hrs %>%
  group_by(t) %>% 
  summarise_at(vars(LOG10N), list(LOG10N = mean)) 
```

```{r}
set.seed(88)
# Three candidate growth models
# 1. buchanan (in log10 scale)
# 2. gompertzm (in log10 scale)
# 3. baranyi (in log10 scale)

# Fit model 1: buchanan_log10
#Preview the curve for setting up starting values of the parameters.
#preview(buchanan_log10, W0.8_10hrs, list(LOG10N0 = 1.59,lag = 42, mumax = 0.02, LOG10Nmax = 7.15))
#Fit the data with the model.
#fitW0.8_10.buc_LM <- nlsLM(buchanan_log10, W0.8_10hrs, trace=T, 
                           #list (LOG10N0 = 1.59,lag = 42, mumax = 0.02, LOG10Nmax = 7.15), 
                           #control = nls.control(maxiter = 100, minFactor = 1/4096, warnOnly = T),
                           #lower = c(LOG10N0 = 0,lag = 0, mumax = 0, LOG10Nmax = 0))
#could not fit to buchanan for 0.8-10C-whole milk

# Fit model 2: gompertzm_log10
preview(gompertzm_log10, W0.8_10hrs, list(LOG10N0 = 1.59,lag = 84, mumax = 0.02, LOG10Nmax = 7.15))
fitW0.8_10.gom_LM <- nlsLM(gompertzm_log10, W0.8_10hrs, trace=T, 
                           list (LOG10N0 = 1.59,lag = 84, mumax = 0.02, LOG10Nmax = 7.15), 
                           control = nls.control(maxiter = 100, minFactor = 1/4096, warnOnly = T),
                           lower = c(LOG10N0 = 0,lag = 0, mumax = 0, LOG10Nmax = 0))


# Fit model 3: baranyi_log10
preview(baranyi_log10, W0.8_10hrs, list(LOG10N0 = 1.59,lag = 84, mumax = 0.02, LOG10Nmax = 7.15))
fitW0.8_10.bar_LM <- nlsLM(baranyi_log10, W0.8_10hrs, trace=T, 
                           list (LOG10N0 = 1.59,lag = 84, mumax = 0.02, LOG10Nmax = 7.15), 
                           control = nls.control(maxiter = 100, minFactor = 1/4096, warnOnly = T),
                           lower = c(LOG10N0 = 0,lag = 0, mumax = 0, LOG10Nmax = 0))



# Compare across models to select the best-fit model.
candidate_models <- list()
#candidate_models[[1]] <- fitW0.8_10.buc_LM
candidate_models[[1]] <- fitW0.8_10.gom_LM
candidate_models[[2]] <- fitW0.8_10.bar_LM
mod.names <- c("Gompertzm", "Baranyi")
output_bic <- bictab(cand.set = candidate_models, modnames = mod.names, sort = TRUE)
print(output_bic)
#both gompertz and baranyi are closest model, average days after calculations

coef(fitW0.8_10.gom_LM)
coef(fitW0.8_10.bar_LM)
```

```{r}
#days to prediction
library(biogrowth)

my_model <- "modGompertz"

primary_model_data("modGompertz")

my_pars <- list(logN0 = 1.59, C = 4.74, mu = 0.17, lambda = 147)

my_time <- seq(0, 840, length = 100)

set.seed(88)

static_prediction <- predict_isothermal_growth(my_model, my_time, my_pars)

static_prediction$simulation

plot(static_prediction) +
  xlab("Storage time (h)") + 
  ylab("Microbial count (log CFU/mL)") +
  theme_gray()

time_to_logcount(static_prediction, 4.301)

time_to_logcount(static_prediction, 6.0)

my_model <- "Baranyi"

primary_model_data("Baranyi")

my_pars <- list(logN0 = 1.59, logNmax = 6.33, mu = 0.046, lambda = 94)

my_time <- seq(0, 840, length = 1000)

static_prediction <- predict_isothermal_growth(my_model, my_time, my_pars)

static_prediction$simulation

plot(static_prediction) +
  xlab("Storage time (h)") + 
  ylab("Microbial count (log CFU/mL)") +
  theme_gray()



time_to_logcount(static_prediction, 4.301)

time_to_logcount(static_prediction, 6.0)

```


###1.2-Whole-10-Overall
```{r}
#1.2-Whole-10c
W1.2_10 <- mfkeep %>% 
  filter(StorageTemp == 10) %>% 
  filter(PoreSize == 1.2) %>% 
  filter(MilkType == "Whole") %>% 
  filter(PlateType == "SPC") %>% 
  dplyr::select(Concentration, Day) %>% 
  filter(!is.na(Concentration)) %>% 
  mutate(Day = Day*24) %>% 
  rename(t = Day) %>% 
  mutate(Concentration = replace(Concentration, Concentration==0, 2.5)) %>%
  mutate(Concentration = log10(Concentration)) %>% 
  rename(LOG10N = Concentration)

W1.2_10hrs <- W1.2_10[c("LOG10N", "t")]

#reorder by column index
W1.2_10hrs <- W1.2_10hrs[c(2,1)]

W1.2_10hrs <- W1.2_10hrs %>%
  group_by(t) %>% 
  summarise_at(vars(LOG10N), list(LOG10N = mean)) 
```

```{r}
set.seed(88)
# Three candidate growth models
# 1. buchanan (in log10 scale)
# 2. gompertzm (in log10 scale)
# 3. baranyi (in log10 scale)

# Fit model 1: buchanan_log10
# Preview the curve for setting up starting values of the parameters.
preview(buchanan_log10, W1.2_10hrs, list(LOG10N0 = 0.96,lag = 84, mumax = 0.016, LOG10Nmax = 7.62))
# Fit the data with the model.
fitW1.2_10.buc_LM <- nlsLM(buchanan_log10, W1.2_10hrs, trace=T, 
                           list (LOG10N0 = 0.96,lag = 84, mumax = 0.016, LOG10Nmax = 7.62), 
                           control = nls.control(maxiter = 100, minFactor = 1/4096, warnOnly = T),
                           lower = c(LOG10N0 = 0,lag = 0, mumax = 0, LOG10Nmax = 0))


# Fit model 2: gompertzm_log10
preview(gompertzm_log10, W1.2_10hrs, list(LOG10N0 = 0.96,lag = 84, mumax = 0.016, LOG10Nmax = 7.62))
fitW1.2_10.gom_LM <- nlsLM(gompertzm_log10, W1.2_10hrs, trace=T, 
                           list (LOG10N0 = 0.96,lag = 84, mumax = 0.016, LOG10Nmax = 7.62), 
                           control = nls.control(maxiter = 100, minFactor = 1/4096, warnOnly = T),
                           lower = c(LOG10N0 = 0,lag = 0, mumax = 0, LOG10Nmax = 0))


# Fit model 3: baranyi_log10
preview(baranyi_log10, W1.2_10hrs, list(LOG10N0 = 0.96,lag = 84, mumax = 0.016, LOG10Nmax = 7.62))
fitW1.2_10.bar_LM <- nlsLM(baranyi_log10, W1.2_10hrs, trace=T, 
                           list (LOG10N0 = 0.96,lag = 42, mumax = 0.016, LOG10Nmax = 7.62), 
                           control = nls.control(maxiter = 100, minFactor = 1/4096, warnOnly = T),
                           lower = c(LOG10N0 = 0,lag = 0, mumax = 0, LOG10Nmax = 0))


# Compare across models to select the best-fit model.
candidate_models <- list()
candidate_models[[1]] <- fitW1.2_10.buc_LM
candidate_models[[2]] <- fitW1.2_10.gom_LM
candidate_models[[3]] <- fitW1.2_10.bar_LM
mod.names <- c("Buchannan", "Gompertzm", "Baranyi")
output_bic <- bictab(cand.set = candidate_models, modnames = mod.names, sort = TRUE)
print(output_bic)

coef(fitW1.2_10.gom_LM)
```

```{r}
library(biogrowth)

my_model <- "modGompertz"

primary_model_data("modGompertz")

my_pars <- list(logN0 = 0.87, C = 6.36, mu = 0.014, lambda = 0)

my_time <- seq(0, 840, length = 1000)

set.seed(88)

static_prediction <- predict_isothermal_growth(my_model, my_time, my_pars)

static_prediction$simulation

plot(static_prediction) +
  xlab("Storage time (h)") + 
  ylab("Microbial count (log CFU/mL)") +
  theme_gray()

time_to_logcount(static_prediction, 4.301)

time_to_logcount(static_prediction, 6.0)

```


###0.8-Whole-6.5-Overall
```{r}

#0.8-Whole-6.5c
W0.8_6.5 <- mfkeep %>% 
  filter(StorageTemp == 6.5) %>% 
  filter(PoreSize == 0.8) %>% 
  filter(MilkType == "Whole") %>% 
  filter(PlateType == "SPC") %>% 
  dplyr::select(Concentration, Day) %>% 
  filter(!is.na(Concentration)) %>% 
  mutate(Day = Day*24) %>% 
  rename(t = Day) %>% 
  mutate(Concentration = replace(Concentration, Concentration==0, 2.5)) %>%
  mutate(Concentration = log10(Concentration)) %>% 
  rename(LOG10N = Concentration)

W0.8_6.5hrs <- W0.8_6.5[c("LOG10N", "t")]

#reorder by column index
W0.8_6.5hrs <- W0.8_6.5hrs[c(2,1)]

W0.8_6.5hrs <- W0.8_6.5hrs %>%
  group_by(t) %>% 
  summarise_at(vars(LOG10N), list(LOG10N = mean)) 
```

```{r}
set.seed(88)
# Three candidate growth models
# 1. buchanan (in log10 scale)
# 2. gompertzm (in log10 scale)
# 3. baranyi (in log10 scale)

# Fit model 1: buchanan_log10
# Preview the curve for setting up starting values of the parameters.
preview(buchanan_log10, W0.8_6.5hrs, list(LOG10N0 = 1.59,lag = 924, mumax = 0.017, LOG10Nmax = 6.02))
# Fit the data with the model.
#fitW0.8_6.5.buc_LM <- nlsLM(buchanan_log10, W0.8_6.5hrs, trace=T, 
                           #list (LOG10N0 = 1.59,lag = 840, mumax = 0.017, LOG10Nmax = 6.02), 
                           #control = nls.control(maxiter = 100, minFactor = 1/4096, warnOnly = T),
                           #lower = c(LOG10N0 = 0,lag = 0, mumax = 0, LOG10Nmax = 0))
# Buchanan does not fit


# Fit model 2: gompertzm_log10
preview(gompertzm_log10, W0.8_6.5hrs, list(LOG10N0 = 1.59,lag = 924, mumax = 0.017, LOG10Nmax = 6.02))
fitW0.8_6.5.gom_LM <- nlsLM(gompertzm_log10, W0.8_6.5hrs, trace=T, 
                           list (LOG10N0 = 1.59,lag = 924, mumax = 0.017, LOG10Nmax = 6.02), 
                           control = nls.control(maxiter = 100, minFactor = 1/4096, warnOnly = T),
                           lower = c(LOG10N0 = 0,lag = 0, mumax = 0, LOG10Nmax = 0))


# Fit model 3: baranyi_log10
preview(baranyi_log10, W0.8_6.5hrs, list(LOG10N0 = 1.59,lag = 924, mumax = 0.017, LOG10Nmax = 6.02))
fitW0.8_6.5.bar_LM <- nlsLM(baranyi_log10, W0.8_6.5hrs, trace=T, 
                           list (LOG10N0 = 1.59,lag = 924, mumax = 0.017, LOG10Nmax = 6.02), 
                           control = nls.control(maxiter = 100, minFactor = 1/4096, warnOnly = T),
                           lower = c(LOG10N0 = 0,lag = 0, mumax = 0, LOG10Nmax = 0))

#does not fit

# Compare across models to select the best-fit model.
candidate_models <- list()
#candidate_models[[1]] <- fitW0.8_10.buc_LM
candidate_models[[1]] <- fitW0.8_6.5.gom_LM
#candidate_models[[2]] <- fitW0.8_6.5.bar_LM
mod.names <- c("Gompertzm")
output_bic <- bictab(cand.set = candidate_models, modnames = mod.names, sort = TRUE)
print(output_bic)

coef(fitW0.8_6.5.gom_LM)
```

```{r}
library(biogrowth)

set.seed(88)

my_model <- "modGompertz"

primary_model_data("modGompertz")

my_pars <- list(logN0 = 1.90, C = 3.88, mu = 0.14, lambda = 989)

my_time <- seq(0, 1500, length = 1000)

static_prediction <- predict_isothermal_growth(my_model, my_time, my_pars)

static_prediction$simulation

plot(static_prediction) +
  xlab("Storage time (h)") + 
  ylab("Microbial count (log CFU/mL)") +
  theme_gray()

time_to_logcount(static_prediction, 4.301)

#time_to_logcount(static_prediction, 6.0)

```


###1.2-Whole-6.5-Overall
```{r}
#1.2-Whole-6.5c
W1.2_6.5 <- mfkeep %>% 
  filter(StorageTemp == 6.5) %>% 
  filter(PoreSize == 1.2) %>% 
  filter(MilkType == "Whole") %>% 
  filter(PlateType == "SPC") %>% 
  dplyr::select(Concentration, Day) %>% 
  filter(!is.na(Concentration)) %>% 
  mutate(Day = Day*24) %>% 
  rename(t = Day) %>% 
  mutate(Concentration = replace(Concentration, Concentration==0, 2.5)) %>%
  mutate(Concentration = log10(Concentration)) %>% 
  rename(LOG10N = Concentration)

W1.2_6.5hrs <- W1.2_6.5[c("LOG10N", "t")]

#reorder by column index
W1.2_6.5hrs <- W1.2_6.5hrs[c(2,1)]

W1.2_6.5hrs <- W1.2_6.5hrs %>%
  group_by(t) %>% 
  summarise_at(vars(LOG10N), list(LOG10N = mean)) 
```

```{r}
set.seed(88)
# Three candidate growth models
# 1. buchanan (in log10 scale)
# 2. gompertzm (in log10 scale)
# 3. baranyi (in log10 scale)


# Fit model 1: buchanan_log10
# Preview the curve for setting up starting values of the parameters.
preview(buchanan_log10, W1.2_6.5hrs, list(LOG10N0 = 0.96,lag = 336, mumax = 0.011, LOG10Nmax = 4.16))
# Fit the data with the model.
#fitW1.2_6.5.buc_LM <- nlsLM(buchanan_log10, W1.2_6.5hrs, trace=T, 
                          #list (LOG10N0 = 0.96,lag = 336, mumax = 0.01, LOG10Nmax = 4.16), 
                           #control = nls.control(maxiter = 100, minFactor = 1/4096, warnOnly = T),
                           #lower = c(LOG10N0 = 0,lag = 0, mumax = 0, LOG10Nmax = 0))
#Buchanan did not work

# Fit model 2: gompertzm_log10
preview(gompertzm_log10, W1.2_6.5hrs, list(LOG10N0 = 0.96,lag = 336, mumax = 0.011, LOG10Nmax = 4.16))
fitW1.2_6.5.gom_LM <- nlsLM(gompertzm_log10, W1.2_6.5hrs, trace=T, 
                           list (LOG10N0 = 0.96,lag = 336, mumax = 0.011, LOG10Nmax = 4.16), 
                           control = nls.control(maxiter = 100, minFactor = 1/4096, warnOnly = T),
                           lower = c(LOG10N0 = 0,lag = 0, mumax = 0, LOG10Nmax = 0))


# Fit model 3: baranyi_log10
preview(baranyi_log10, W1.2_6.5hrs, list(LOG10N0 = 0.96,lag = 336, mumax = 0.011, LOG10Nmax = 4.16))
fitW1.2_6.5.bar_LM <- nlsLM(baranyi_log10, W1.2_6.5hrs, trace=T, 
                           list (LOG10N0 = 0.96,lag = 336, mumax = 0.011, LOG10Nmax = 4.16), 
                           control = nls.control(maxiter = 100, minFactor = 1/4096, warnOnly = T),
                           lower = c(LOG10N0 = 0,lag = 0, mumax = 0, LOG10Nmax = 0))


# Compare across models to select the best-fit model.
candidate_models <- list()
#candidate_models[[1]] <- fitW1.2_10.buc_LM
candidate_models[[1]] <- fitW1.2_6.5.gom_LM
candidate_models[[2]] <- fitW1.2_6.5.bar_LM
mod.names <- c("Gompertzm", "Baranyi")
output_bic <- bictab(cand.set = candidate_models, modnames = mod.names, sort = TRUE)
print(output_bic)

coef(fitW1.2_6.5.gom_LM)

```

```{r}
library(biogrowth)

set.seed(88)

my_model <- "modGompertz"

primary_model_data("modGompertz")

my_pars <- list(logN0 = 0, C = 4.16, mu = 0.0046, lambda = 962)

my_time <- seq(0, 2000, length = 2000)

static_prediction <- predict_isothermal_growth(my_model, my_time, my_pars)

static_prediction$simulation

plot(static_prediction) +
  xlab("Storage time (h)") + 
  ylab("Microbial count (log CFU/mL)") +
  theme_gray()

#used observed Nmax of whole-1.2-6.5C (4.16 log) given the predicted was 37 log
time_to_logcount(static_prediction, 4.301)

#time_to_logcount(static_prediction, 6.0)

```


###0.8-Skim-10-Overall
```{r}
##Filter by storage/HTST temp
#0.8-Skim-10c
S0.8_10 <- mfkeep %>% 
  filter(StorageTemp == 10) %>% 
  filter(PoreSize == 0.8) %>% 
  filter(MilkType == "Skim") %>% 
  filter(PlateType == "SPC") %>% 
  dplyr::select(Concentration, Day) %>% 
  filter(!is.na(Concentration)) %>% 
  mutate(Day = Day*24) %>% 
  rename(t = Day) %>% 
  mutate(Concentration = replace(Concentration, Concentration==0, 2.5)) %>%
  mutate(Concentration = log10(Concentration)) %>% 
  rename(LOG10N = Concentration)

S0.8_10hrs <- S0.8_10[c("LOG10N", "t")]

#reorder by column index
S0.8_10hrs <- S0.8_10hrs[c(2,1)]

S0.8_10hrs <- S0.8_10hrs %>%
  group_by(t) %>% 
  summarise_at(vars(LOG10N), list(LOG10N = mean)) 
```

```{r}
set.seed(88)
# Three candidate growth models
# 1. buchanan (in log10 scale)
# 2. gompertzm (in log10 scale)
# 3. baranyi (in log10 scale)

# Fit model 1: buchanan_log10
# Preview the curve for setting up starting values of the parameters.
#preview(buchanan_log10, S0.8_10hrs, list(LOG10N0 = 1.67,lag = 168, mumax = 0.025, LOG10Nmax = 8.05))
# Fit the data with the model.
#fitS0.8_10.buc_LM <- nlsLM(buchanan_log10, S0.8_10hrs, trace=T, 
                        #   list (LOG10N0 = 1.67,lag = 168, mumax = 0.025, LOG10Nmax = 8.05), 
                       #    control = nls.control(maxiter = 100, minFactor = 1/4096, warnOnly = T),
                        #   lower = c(LOG10N0 = 0,lag = 0, mumax = 0, LOG10Nmax = 0))

#buchanan did not fit

# Fit model 2: gompertzm_log10
preview(gompertzm_log10, S0.8_10hrs, list(LOG10N0 = 1.67,lag = 252, mumax = 0.025, LOG10Nmax = 8.05))
fitS0.8_10.gom_LM <- nlsLM(gompertzm_log10, S0.8_10hrs, trace=T, 
                           list (LOG10N0 = 1.67,lag = 252, mumax = 0.025, LOG10Nmax = 8.05), 
                           control = nls.control(maxiter = 100, minFactor = 1/4096, warnOnly = T),
                           lower = c(LOG10N0 = 0,lag = 0, mumax = 0, LOG10Nmax = 0))



# Fit model 3: baranyi_log10
preview(baranyi_log10, S0.8_10hrs, list(LOG10N0 = 1.67,lag = 252, mumax = 0.025, LOG10Nmax = 8.05))
fitS0.8_10.bar_LM <- nlsLM(baranyi_log10, S0.8_10hrs, trace=T, 
                           list (LOG10N0 = 1.67,lag = 252, mumax = 0.025, LOG10Nmax = 8.05), 
                           control = nls.control(maxiter = 100, minFactor = 1/4096, warnOnly = T),
                           lower = c(LOG10N0 = 0,lag = 0, mumax = 0, LOG10Nmax = 0))



# Compare across models to select the best-fit model.
candidate_models <- list()
#candidate_models[[1]] <- fitS0.8_10.buc_LM
candidate_models[[1]] <- fitS0.8_10.gom_LM
candidate_models[[2]] <- fitS0.8_10.bar_LM
mod.names <- c("Gompertzm", "Baranyi")
output_bic <- bictab(cand.set = candidate_models, modnames = mod.names, sort = TRUE)
print(output_bic)


coef(fitS0.8_10.gom_LM)

```

```{r}
library(biogrowth)

set.seed(88)
my_model <- "modGompertz"

primary_model_data("modGompertz")

my_pars <- list(logN0 = 1.66, C = 5.48, mu = 0.037, lambda = 144)

my_time <- seq(0, 1000, length = 1000)

static_prediction <- predict_isothermal_growth(my_model, my_time, my_pars)

static_prediction$simulation

plot(static_prediction) +
  xlab("Storage time (h)") + 
  ylab("Microbial count (log CFU/mL)") +
  theme_gray()

time_to_logcount(static_prediction, 4.301)

time_to_logcount(static_prediction, 6.0)

```


###1.2-Skim-10-Overall
```{r}
##Filter by storage/HTST temp

#1.2-Skim-10c
S1.2_10 <- mfkeep %>% 
  filter(StorageTemp == 10) %>% 
  filter(PoreSize == 1.2) %>% 
  filter(MilkType == "Skim") %>% 
  filter(PlateType == "SPC") %>% 
  dplyr::select(Concentration, Day) %>% 
  filter(!is.na(Concentration)) %>% 
  mutate(Day = Day*24) %>% 
  rename(t = Day) %>% 
  mutate(Concentration = replace(Concentration, Concentration==0, 2.5)) %>%
  mutate(Concentration = log10(Concentration)) %>% 
  rename(LOG10N = Concentration)

S1.2_10hrs <- S1.2_10[c("LOG10N", "t")]

#reorder by column index
S1.2_10hrs <- S1.2_10hrs[c(2,1)]

S1.2_10hrs <- S1.2_10hrs %>%
  group_by(t) %>% 
  summarise_at(vars(LOG10N), list(LOG10N = mean)) 
```

```{r}
# Three candidate growth models
# 1. buchanan (in log10 scale)
# 2. gompertzm (in log10 scale)
# 3. baranyi (in log10 scale)

# Fit model 1: buchanan_log10
# Preview the curve for setting up starting values of the parameters.
#preview(buchanan_log10, S1.2_10hrs, list(LOG10N0 = 0.51,lag = 168, mumax = 0.018, LOG10Nmax = 6.37))
# Fit the data with the model.
#fitS1.2_10.buc_LM <- nlsLM(buchanan_log10, S1.2_10hrs, trace=T, 
                         #  list (LOG10N0 = 0.51,lag = 168, mumax = 0.018, LOG10Nmax = 6.37), 
                          # control = nls.control(maxiter = 100, minFactor = 1/4096, warnOnly = T),
                          # lower = c(LOG10N0 = 0,lag = 0, mumax = 0, LOG10Nmax = 0))

#could not fit buchannan

# Fit model 2: gompertzm_log10
preview(gompertzm_log10, S1.2_10hrs, list(LOG10N0 = 0.51,lag = 252, mumax = 0.018, LOG10Nmax = 6.37))
fitS1.2_10.gom_LM <- nlsLM(gompertzm_log10, S1.2_10hrs, trace=T, 
                           list (LOG10N0 = 0.51,lag = 252, mumax = 0.018, LOG10Nmax = 6.37), 
                           control = nls.control(maxiter = 100, minFactor = 1/4096, warnOnly = T),
                           lower = c(LOG10N0 = 0,lag = 0, mumax = 0, LOG10Nmax = 0))



# Fit model 3: baranyi_log10
preview(baranyi_log10, S1.2_10hrs, list(LOG10N0 = 0.51,lag = 252, mumax = 0.018, LOG10Nmax = 6.37))
fitS1.2_10.bar_LM <- nlsLM(baranyi_log10, S1.2_10hrs, trace=T, 
                           list (LOG10N0 = 0.51,lag = 252, mumax = 0.018, LOG10Nmax = 6.37), 
                           control = nls.control(maxiter = 100, minFactor = 1/4096, warnOnly = T),
                           lower = c(LOG10N0 = 0,lag = 0, mumax = 0, LOG10Nmax = 0))



# Compare across models to select the best-fit model.
candidate_models <- list()
#candidate_models[[1]] <- fitS1.2_10.buc_LM
candidate_models[[1]] <- fitS1.2_10.gom_LM
candidate_models[[2]] <- fitS1.2_10.bar_LM
mod.names <- c("Gompertzm", "Baranyi")
output_bic <- bictab(cand.set = candidate_models, modnames = mod.names, sort = TRUE)
print(output_bic)


coef(fitS1.2_10.gom_LM)

```

```{r}
library(biogrowth)

set.seed(88)
my_model <- "modGompertz"

primary_model_data("modGompertz")

#predicted Nmax was below 6 log and was not getting time to 1 million. Switched to obsereved Nmax (6.37 log) to get time to 1 mil.    
my_pars <- list(logN0 = 0.36, C = 6.01, mu = 0.013, lambda = 121)

my_time <- seq(0, 1000, length = 1000)

static_prediction <- predict_isothermal_growth(my_model, my_time, my_pars)

static_prediction$simulation

plot(static_prediction) +
  xlab("Storage time (h)") + 
  ylab("Microbial count (log CFU/mL)") +
  theme_gray()

time_to_logcount(static_prediction, 4.301)

time_to_logcount(static_prediction, 6.0)

```


###0.8-Skim-6.5-Overall
```{r}
#0.8-Skim-6.5c
S0.8_6.5 <- mfkeep %>% 
  filter(StorageTemp == 6.5) %>% 
  filter(PoreSize == 0.8) %>% 
  filter(MilkType == "Skim") %>% 
  filter(PlateType == "SPC") %>% 
  dplyr::select(Concentration, Day) %>% 
  filter(!is.na(Concentration)) %>% 
  mutate(Day = Day*24) %>% 
  rename(t = Day) %>% 
  mutate(Concentration = replace(Concentration, Concentration==0, 2.5)) %>%
  mutate(Concentration = log10(Concentration)) %>% 
  rename(LOG10N = Concentration)

S0.8_6.5hrs <- S0.8_6.5[c("LOG10N", "t")]

#reorder by column index
S0.8_6.5hrs <- S0.8_6.5hrs[c(2,1)]

S0.8_6.5hrs <- S0.8_6.5hrs %>%
  group_by(t) %>% 
  summarise_at(vars(LOG10N), list(LOG10N = mean)) 
```

```{r}
set.seed(88)
# Three candidate growth models
# 1. buchanan (in log10 scale)
# 2. gompertzm (in log10 scale)
# 3. baranyi (in log10 scale)

# Fit model 1: buchanan_log10
# Preview the curve for setting up starting values of the parameters.
preview(buchanan_log10, S0.8_6.5hrs, list(LOG10N0 = 1.67,lag = 756, mumax = 0.012, LOG10Nmax = 5.58))
# Fit the data with the model.
#fitS0.8_6.5.buc_LM <- nlsLM(buchanan_log10, S0.8_6.5hrs, trace=T, 
                          # list (LOG10N0 = 1.67,lag = 672, mumax = 0.012, LOG10Nmax = 5.58), 
                           #control = nls.control(maxiter = 100, minFactor = 1/4096, warnOnly = T),
                           #lower = c(LOG10N0 = 0,lag = 0, mumax = 0, LOG10Nmax = 0))
#could not fit to buchanan for 0.8-6.5C-Skim

# Fit model 2: gompertzm_log10
preview(gompertzm_log10, S0.8_6.5hrs, list(LOG10N0 = 1.67,lag = 756, mumax = 0.012, LOG10Nmax = 5.58))
fitS0.8_6.5.gom_LM <- nlsLM(gompertzm_log10, S0.8_6.5hrs, trace=T, 
                           list (LOG10N0 = 1.67,lag = 756, mumax = 0.012, LOG10Nmax = 5.58), 
                           control = nls.control(maxiter = 100, minFactor = 1/4096, warnOnly = T),
                           lower = c(LOG10N0 = 0,lag = 0, mumax = 0, LOG10Nmax = 0))


# Fit model 3: baranyi_log10
preview(baranyi_log10, S0.8_6.5hrs, list(LOG10N0 = 1.67,lag = 756, mumax = 0.012, LOG10Nmax = 5.58))
fitS0.8_6.5.bar_LM <- nlsLM(baranyi_log10, S0.8_6.5hrs, trace=T, 
                           list (LOG10N0 = 1.67,lag = 756, mumax = 0.012, LOG10Nmax = 5.58), 
                           control = nls.control(maxiter = 100, minFactor = 1/4096, warnOnly = T),
                           lower = c(LOG10N0 = 0,lag = 0, mumax = 0, LOG10Nmax = 0))


# Compare across models to select the best-fit model.
candidate_models <- list()
#candidate_models[[1]] <- fitW0.8_10.buc_LM
#candidate_models[[2]] <- fitl3051_C.buc_nl_LM
candidate_models[[1]] <- fitS0.8_6.5.gom_LM
candidate_models[[2]] <- fitS0.8_6.5.bar_LM
#candidate_models[[5]] <- fitl3051_C.bar_nl_LM
mod.names <- c("Gompertzm", "Baranyi")
output_bic <- bictab(cand.set = candidate_models, modnames = mod.names, sort = TRUE)
print(output_bic)
#baranyi is closest model

coef(fitS0.8_6.5.bar_LM)

```

```{r}
library(biogrowth)

set.seed(88)

my_model <- "Baranyi"

primary_model_data("Baranyi")

my_pars <- list(logN0 = 1.76, logNmax = 5.15, mu = 0.018, lambda = 722)

my_time <- seq(0, 2000, length = 1000)

static_prediction <- predict_isothermal_growth(my_model, my_time, my_pars)

static_prediction$simulation

plot(static_prediction) +
  xlab("Storage time (h)") + 
  ylab("Microbial count (log CFU/mL)") +
  theme_gray()

time_to_logcount(static_prediction, 4.301)

#time_to_logcount(static_prediction, 6.0)

```


###1.2-Skim-6.5-Overall
```{r}

#1.2-Skim-6.5c
S1.2_6.5 <- mfkeep %>% 
  filter(StorageTemp == 6.5) %>% 
  filter(PoreSize == 1.2) %>% 
  filter(MilkType == "Skim") %>% 
  filter(PlateType == "SPC") %>% 
  dplyr::select(Concentration, Day) %>% 
  filter(!is.na(Concentration)) %>% 
  mutate(Day = Day*24) %>% 
  rename(t = Day) %>% 
  mutate(Concentration = replace(Concentration, Concentration==0, 2.5)) %>%
  mutate(Concentration = log10(Concentration)) %>% 
  rename(LOG10N = Concentration)

S1.2_6.5hrs <- S1.2_6.5[c("LOG10N", "t")]

#reorder by column index
S1.2_6.5hrs <- S1.2_6.5hrs[c(2,1)]

S1.2_6.5hrs <- S1.2_6.5hrs %>%
  group_by(t) %>% 
  summarise_at(vars(LOG10N), list(LOG10N = mean)) 
```

```{r}
set.seed(88)
# Three candidate growth models
# 1. buchanan (in log10 scale)
# 2. gompertzm (in log10 scale)
# 3. baranyi (in log10 scale)

# Fit model 1: buchanan_log10
# Preview the curve for setting up starting values of the parameters.
preview(buchanan_log10, S1.2_6.5hrs, list(LOG10N0 = 0.51,lag = 336, mumax = 0.0054, LOG10Nmax = 2.91))
# Fit the data with the model.
fitS1.2_6.5.buc_LM <- nlsLM(buchanan_log10, S1.2_6.5hrs, trace=T, 
                           list (LOG10N0 = 0.51,lag = 336, mumax = 0.0054, LOG10Nmax = 2.91), 
                           control = nls.control(maxiter = 100, minFactor = 1/4096, warnOnly = T),
                           lower = c(LOG10N0 = 0,lag = 0, mumax = 0, LOG10Nmax = 0))

# Fit model 2: gompertzm_log10
preview(gompertzm_log10, S1.2_6.5hrs, list(LOG10N0 = 0.51,lag = 336, mumax = 0.0054, LOG10Nmax = 2.91))
fitS1.2_6.5.gom_LM <- nlsLM(gompertzm_log10, S1.2_6.5hrs, trace=T, 
                           list (LOG10N0 = 0.51,lag = 336, mumax = 0.0054, LOG10Nmax = 2.91), 
                           control = nls.control(maxiter = 100, minFactor = 1/4096, warnOnly = T),
                           lower = c(LOG10N0 = 0,lag = 0, mumax = 0, LOG10Nmax = 0))



# Fit model 3: baranyi_log10
preview(baranyi_log10, S1.2_6.5hrs, list(LOG10N0 = 0.51,lag = 336, mumax = 0.0054, LOG10Nmax = 2.91))
fitS1.2_6.5.bar_LM <- nlsLM(baranyi_log10, S1.2_6.5hrs, trace=T, 
                           list (LOG10N0 = 0.51,lag = 336, mumax = 0.0054, LOG10Nmax = 2.91), 
                           control = nls.control(maxiter = 100, minFactor = 1/4096, warnOnly = T),
                           lower = c(LOG10N0 = 0,lag = 0, mumax = 0, LOG10Nmax = 0))



# Compare across models to select the best-fit model.
candidate_models <- list()
candidate_models[[1]] <- fitS1.2_6.5.buc_LM
candidate_models[[2]] <- fitS1.2_6.5.gom_LM
candidate_models[[3]] <- fitS1.2_6.5.bar_LM
mod.names <- c("Buchanan", "Gompertzm", "Baranyi")
output_bic <- bictab(cand.set = candidate_models, modnames = mod.names, sort = TRUE)
print(output_bic)

coef(fitS1.2_6.5.bar_LM)

```

```{r}
library(biogrowth)

my_model <- "Baranyi"

primary_model_data("Baranyi")

my_pars <- list(logN0 = 0.51, logNmax = 1.96, mu = 0.0036, lambda = 354)

my_time <- seq(0, 10000, length = 1000)

set.seed(88)

static_prediction <- predict_isothermal_growth(my_model, my_time, my_pars)

static_prediction$simulation

plot(static_prediction) +
  xlab("Storage time (h)") + 
  ylab("Microbial count (log CFU/mL)") +
  theme_gray()

time_to_logcount(static_prediction, 4.301)

time_to_logcount(static_prediction, 6.0)

```





